const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');

const OUTPUT_DIR = path.join(__dirname, '..', 'uploads', 'reports');
if (!fs.existsSync(OUTPUT_DIR)) fs.mkdirSync(OUTPUT_DIR, { recursive: true });

/**
 * Generates a professional PDF report from a list of articles.
 * Returns { filePath, fileName, fileSize }.
 */
function generateReportPdf({ articles, generatedBy, orgName = 'News Monitoring System', orgLogoPath, title }) {
  return new Promise((resolve, reject) => {
    const fileName = `report-${Date.now()}.pdf`;
    const filePath = path.join(OUTPUT_DIR, fileName);
    const doc = new PDFDocument({ margin: 50, bufferPages: true, size: 'A4' });
    const stream = fs.createWriteStream(filePath);
    doc.pipe(stream);

    const addFooter = () => {
      const range = doc.bufferedPageRange();
      for (let i = range.start; i < range.start + range.count; i++) {
        doc.switchToPage(i);
        doc
          .fontSize(8)
          .fillColor('#888')
          .text(`${orgName} — Confidential`, 50, doc.page.height - 40, { align: 'left' })
          .text(`Page ${i + 1} of ${range.count}`, 0, doc.page.height - 40, { align: 'right', width: doc.page.width - 50 });
        // Watermark
        doc.save();
        doc.rotate(-45, { origin: [doc.page.width / 2, doc.page.height / 2] });
        doc.fontSize(60).fillColor('#f0f0f0').text('CONFIDENTIAL', doc.page.width / 2 - 200, doc.page.height / 2 - 30, { opacity: 0.15 });
        doc.restore();
      }
    };

    // --- Cover / header ---
    if (orgLogoPath && fs.existsSync(orgLogoPath)) {
      doc.image(orgLogoPath, 50, 45, { width: 60 });
    }
    doc.fontSize(20).fillColor('#111').text(orgName, 120, 50);
    doc.fontSize(10).fillColor('#555').text(title || 'Industry News Report', 120, 75);
    doc.moveDown(2);
    doc.fontSize(10).fillColor('#333');
    doc.text(`Generated by: ${generatedBy}`);
    doc.text(`Generated on: ${new Date().toLocaleString()}`);
    doc.text(`Total articles: ${articles.length}`);
    doc.moveDown(1);
    doc.strokeColor('#ddd').moveTo(50, doc.y).lineTo(doc.page.width - 50, doc.y).stroke();

    // --- Table of contents ---
    doc.addPage();
    doc.fontSize(16).fillColor('#111').text('Table of Contents', { underline: true });
    doc.moveDown(0.5);
    articles.forEach((a, idx) => {
      doc.fontSize(10).fillColor('#333').text(`${idx + 1}. ${a.title}  —  ${a.publisher}`);
    });

    // --- Summary page ---
    doc.addPage();
    doc.fontSize(16).fillColor('#111').text('Executive Summary', { underline: true });
    doc.moveDown(0.5);
    const byPublisher = {};
    articles.forEach((a) => { byPublisher[a.publisher] = (byPublisher[a.publisher] || 0) + 1; });
    doc.fontSize(10).fillColor('#333');
    Object.entries(byPublisher).forEach(([pub, count]) => {
      doc.text(`${pub}: ${count} article(s)`);
    });

    // --- Articles ---
    articles.forEach((a, idx) => {
      doc.addPage();
      doc.fontSize(14).fillColor('#111').text(`${idx + 1}. ${a.title}`);
      doc.moveDown(0.3);
      doc.fontSize(9).fillColor('#666').text(
        `${a.publisher}  |  ${a.publishedDate ? new Date(a.publishedDate).toDateString() : ''}  |  ${a.language || ''}`
      );
      doc.moveDown(0.5);
      if (a.imageUrl && a.localImagePath && fs.existsSync(a.localImagePath)) {
        try { doc.image(a.localImagePath, { width: 200 }); doc.moveDown(0.5); } catch (_) {}
      }
      doc.fontSize(10).fillColor('#333').text(a.description || 'No description available.', { align: 'justify' });
      doc.moveDown(0.5);
      doc.fontSize(9).fillColor('#1a56db').text(a.url, { link: a.url, underline: true });
    });

    addFooter();
    doc.end();

    stream.on('finish', () => {
      const fileSize = fs.statSync(filePath).size;
      resolve({ filePath, fileName, fileSize });
    });
    stream.on('error', reject);
  });
}

module.exports = { generateReportPdf, OUTPUT_DIR };
